url: 'https://abusinglinux.com/'
title: AbusingLinux
author: isuckatlinux
email: pedroluisgarciamontil@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi, Im Pedro García a cybersecurity and ethical hacking learner.
  I will be sharing on this web site all my knowledge of these particular arts.
  I hope you enjoy this blog as much as I do writting all this! <3
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: https://abusinglinux.com/

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/ISuckAtLinuxxx
      icon: twitter-square
      color: cyan
    - url: https://github.com/isuckatlinux
      icon: github-square
      color: purple

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: isuckatlinux
  avatar_source: local
  avatar_path: /assets/linux.gif

# Build settings
# theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
